world_queries/app/models.py
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from config import db

class Country(db.Model):
    __tablename__ = 'country'

    # Campos de la tabla
    Code = db.Column(db.String(3), primary_key=True)  # Llave primaria
    Name = db.Column(db.String(52))  # Nombre del país
    Continent = db.Column(
        db.Enum('Asia', 'Europe', 'North America', 'Africa', 
                'South America', 'Oceania', 'Antarctica', 
                name='continent_enum'), 
        nullable=False, default='Asia'
    )  # Continente como Enum
    Region = db.Column(db.String(26))  # Región
    SurfaceArea = db.Column(db.Numeric(10, 2))  # Área superficial
    IndepYear = db.Column(db.SmallInteger, nullable=True)  # Año de independencia
    Population = db.Column(db.Integer)  # Población
    LifeExpectancy = db.Column(db.Numeric(3, 1), nullable=True)  # Esperanza de vida
    GNP = db.Column(db.Numeric(10, 2), nullable=True)  # Producto Nacional Bruto
    GNPOld = db.Column(db.Numeric(10, 2), nullable=True)  # GNP antiguo
    LocalName = db.Column(db.String(45))  # Nombre local
    GovernmentForm = db.Column(db.String(45))  # Forma de gobierno
    HeadOfState = db.Column(db.String(60), nullable=True)  # Jefe de estado
    Capital = db.Column(db.Integer, ForeignKey('city.ID'), nullable=True)  # Capital (clave foránea a `City`)
    Code2 = db.Column(db.String(2))  # Código ISO de 2 caracteres

     # Relación con tablas
    cities = relationship(
        'City', 
        back_populates='country', 
        foreign_keys='City.CountryCode'
    )

    languages = relationship(
        'CountryLanguage', 
        back_populates='country', 
        foreign_keys='CountryLanguage.CountryCode'
    )

class City(db.Model):
    __tablename__ = 'city'

    # Campos de la tabla
    ID = db.Column(db.Integer, primary_key=True) # Clave primaria con auto-incremento
    Name = db.Column(db.String(35)) # Nombre de la ciudad
    CountryCode = db.Column(db.String(3), ForeignKey('country.Code')) # Llave foránea)
    District = db.Column(db.String(20)) # Distrito
    Population = db.Column(db.Integer) # Población de la ciudad
    
    # Relación con la tabla Country
    country = relationship(
        'Country', 
        back_populates='cities', 
        foreign_keys=[CountryCode]
    )
    
    
class CountryLanguage(db.Model):
    __tablename__ = 'countrylanguage'

    # Clave primaria compuesta
    CountryCode = db.Column(db.String(3), ForeignKey('country.Code'), primary_key=True)  # Relación con `Country`
    Language = db.Column(db.String(30), primary_key=True)  # Idioma (clave primaria)
    IsOfficial = db.Column(db.Enum('T', 'F', name='is_official_enum'))  # Si es oficial o no
    Percentage = db.Column(db.Numeric(4, 1))  # Porcentaje de hablantes

    # Relación con la tabla Country
    country = relationship(
        'Country', 
        back_populates='languages', 
        foreign_keys=[CountryCode]
    )

world_queries/app/__init__.py
# Inicializa la aplicación Flask, configura SQLAlchemy y establece las 
# configuraciones necesarias para conectarse a la base de datos World.
from flask import Flask, render_template
from .views import views
from config import db


def create_app():
    # Crea una instancia de la aplicación Flask
    app = Flask(__name__)
    app.register_blueprint(views)
    
    #Configura la base de datos
    app.config["SQLALCHEMY_DATABASE_URI"] = 'mysql://root:@localhost/world'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)

    @app.errorhandler(404)
    def page_not_found(error):
     # Renderiza el template '404.html' en caso de que la página no sea encontrada
        return render_template('404.html'), 404
    
    return app  # Retorna la instancia de la aplicación

world_queries/app/views.py
#VIEWS
#Este archivo meneja las rutas de Flask, llamando a funciones de consulta y pasando los resultados a templates.
from flask import render_template
from flask import Blueprint,request
from .queries import cons1,cons2,cons3,cons4,cons5,cons6


views = Blueprint('views', __name__)

# Define la ruta de inicio
@views.route('/')  
# Decorador para definir la ruta raíz
def index():
    # Renderiza el template 'index.html'
    return render_template('index.html')


# Define la ruta de about
@views.route('/about')  
# Decorador para definir la ruta about
def about():
    # Renderiza el template 'index.html'
    return render_template('about.html')


# Define a helper to get the nested key value
def get_nested_value(item, key):
    keys = key.split('.')  # Intepreta notacion con .
    for k in keys:
        item = item.get(k)  # Navega al siguiente nivel
        if item is None:
            return None  # Regresa nad si la llave es nula
    return item


# Define la ruta de consulta1
@views.route('/1',methods=['GET'])  
# Decorador para definir la ruta consulta1
def c1():
    #Importa datos y los ordena
    data = cons1()
    sort_by = request.args.get('sort_by','population')
    sort_order = request.args.get('sort_order', 'desc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    # Renderiza el template con datos ordenados
    return render_template('consulta_1.html', results=sorted_data)


# Define la ruta de consulta2
@views.route('/2',methods=['GET'])  
# Decorador para definir la ruta consulta2
def c2():
    #Importa datos y los ordena
    data = cons2()
    sort_by = request.args.get('sort_by','Percentage')
    sort_order = request.args.get('sort_order', 'desc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    print(sorted_data)
    # Renderiza el template con datos ordenados
    return render_template('consulta_2.html', results=sorted_data)

# Define la ruta de consulta3
@views.route('/3')  
# Decorador para definir la ruta consulta3
def c3():
    #Importa datos y los ordena
    data = cons3()
    sort_by = request.args.get('sort_by','pdensity')
    sort_order = request.args.get('sort_order', 'desc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    print(sorted_data)
    # Renderiza el template con datos ordenados
    return render_template('consulta_3.html', results=sorted_data)

# Define la ruta de consulta4
@views.route('/4')  
# Decorador para definir la ruta consulta4
def c4():
    #Importa datos y los ordena
    data = cons4()
    sort_by = request.args.get('sort_by','population')
    sort_order = request.args.get('sort_order', 'asc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    print(sorted_data)
    # Renderiza el template con datos ordenados
    return render_template('consulta_4.html', results=sorted_data)


# Define la ruta de consulta5
@views.route('/5')  
# Decorador para definir la ruta consulta5
def c5():
    #Importa datos y los ordena
    data = cons5()
    sort_by = request.args.get('sort_by','gnp')
    sort_order = request.args.get('sort_order', 'desc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    print(sorted_data)
    # Renderiza el template con datos ordenados
    return render_template('consulta_5.html', results=sorted_data)

# Define la ruta de consulta5
@views.route('/6')  
# Decorador para definir la ruta consulta5
def c6():
    #Importa datos y los ordena
    data = cons6()
    sort_by = request.args.get('sort_by','percentage')
    sort_order = request.args.get('sort_order', 'desc')
    reverse = True if sort_order == 'desc' else False

    #Intenta ordenar los datos
    try:
        sorted_data = sorted(data, key=lambda x: get_nested_value(x,sort_by), reverse=reverse)
    except Exception as e:
        print(f"Error during sorting: {e}")
        sorted_data = data 

    print(sorted_data)
    # Renderiza el template con datos ordenados
    return render_template('consulta_6.html', results=sorted_data)

world_queries/app/templates/_navigation.html
<!-- <nav>
    <a href=" url_for('index'">Inicio</a>
    <a href=" url_for('consulta_1')">Consulta 1</a>
    <a href=" url_for('consulta_2')">Consulta 2</a>
    <a href=" url_for('consulta_3')">Consulta 3</a>
    <a href=" url_for('consulta_4')">Consulta 4</a>
    <a href=" url_for('consulta_5')">Consulta 5</a>
</nav> -->

<nav class="navbar navbar-dark  relative-top">
    <div class="container-fluid  justify-content-start">
        <!-- BOTÓN MENÚ -->
        <div class="d-flex">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand px-3 link color5" href="{{ url_for('views.index') }}">W<i class="bi bi-globe-americas color5"></i>RLD QUERIES</a>
        </div>

      <!-- OFFCANVAS -->
        <div class="offcanvas offcanvas-start color5" tabindex="-1" id="menu" style="background-color: #728156;">
            <div class="offcanvas-header justify-content-evenly mt-3">
                <h5 class="color5">W<i class="bi bi-globe-americas color5"></i>RLD QUERIES</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <hr class="text-white">
        <!-- ENLACES -->
            <div class="offcanvas-body d-flex flex-column justify-content-between ps-5">
                <ul class="navbar-nav justify-content-start fs-4">
                    <li class="nav-item">
                        <a class="nav-link link" aria-current="page" href="/">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Consultas
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark fs-5">
                            <li><a class="dropdown-item" href="{{ url_for('views.c1') }}">Consulta 1</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('views.c2') }}">Consulta 2</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('views.c3') }}">Consulta 3</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('views.c4') }}">Consulta 4</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('views.c5') }}">Consulta 5</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('views.c6') }}">Consulta 6</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link" href="{{ url_for('views.about') }}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
  </nav>

world_queries/app/templates/about.html
{% extends './decorated_base.html' %} 
    {% block datatext %}
    <div class="container-fluid text-center my-5">
        <h2 class="color1">Descripción del proyecto</h2>
        <div class="container-lg text-justify py-5 fw-light">
            <p>
                El proyecto consiste en desarrollar una aplicación web utilizando el framework Flask que permita realizar consultas avanzadas a la base de datos World de MySQL. Esta base de datos está compuesta por las tablas country, city y countrylanguage, las cuales están interrelacionadas mediante claves foráneas.
            </p>
            <p> 
                La aplicación será diseñada siguiendo el patrón de arquitectura Modelo-Vista-Controlador (MVC), lo que garantiza una separación clara entre la lógica de negocio, la presentación y el acceso a los datos. Además, se empleará SQLAlchemy para modelar las tablas, gestionar las relaciones y realizar las consultas necesarias. Los resultados de estas consultas se presentarán en el navegador utilizando plantillas dinámicas generadas con Jinja2.
            </p>
            <p>
                El objetivo principal es implementar cinco consultas complejas que combinen datos de las tablas mencionadas y brindar una interfaz intuitiva que permita al usuario interactuar con dichas consultas.
            </p>
            <p>
                Este proyecto busca desarrollar habilidades prácticas en diseño de bases de datos, implementación de aplicaciones web y organización del código bajo estándares profesionales.
            </p>
        </div>
    </div>
    {% endblock %}

world_queries/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- FUNTES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kantumruy+Pro:ital,wght@0,100..700;1,100..700&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    <!-- CSS PROPIO -->
    <link rel="stylesheet" href="{{ url_for ('static', filename='style.css') }}">
    <title>{% block title%} {%endblock%}</title>
</head>
<body>
    {% include '_navigation.html' %}
    {% block content %}
      
    {% endblock %} 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
<footer class="container-fluid text-center py-3 color3"> 
    <div class="footer-content">
        <p class="text-uppercase" style="opacity: 0.8; font-size: 1rem;"> Elaborado por <i class="bi bi-person-wheelchair"></i> <br>
            Leonardo Velasco Ojeda & Fernando Revilla Torres
        </p>
    </div>
</footer>
</html>

world_queries/app/templates/consulta_1.html
{% extends './decorated_base.html' %} 
    {% block datatext %}
    <div class="container-fluid text-center my-5">
        <div style="text-align: center;">
            <h2 class="color1">CONSULTA 1</h2>
            <h6 class="color6 fw-light">Ciudades europeas donde la población es mayor a la media mundial.</h6>
        </div>
        <div  class="container-md table-container shadow rounded-5" style="overflow: auto;">
            <form  method="GET" action="/1">
                <div class="row mb-3">
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_by">Sort by:</label>
                        <select class="form-select" name="sort_by" id="sort_by">
                            <option value="city" {% if request.args.get('sort_by', 'population') == 'city' %}selected{% endif %}>City</option>
                            <option value="country" {% if request.args.get('sort_by', 'population') == 'country' %}selected{% endif %}>Country</option>
                            <option value="population" {% if request.args.get('sort_by', 'population') == 'population' %}selected{% endif %}>Population</option>
                        </select>
                    </div>
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_order">Order:</label>
                        <select class="form-select" name="sort_order" id="sort_order">
                            <option value="asc" {% if request.args.get('sort_order', 'desc') == 'asc' %}selected{% endif %}>Ascending</option>
                            <option value="desc" {% if request.args.get('sort_order', 'desc') == 'desc' %}selected{% endif %}>Descending</option>
                        </select>
                    </div>
                    <div class="col-sm-2 align-middle">
                        <button class="btn btn-secondary" type="submit">Sort</button>
                    </div>
                </div>
            </form>

            <table class="table table-striped table-hover table-borderless " style="background-color: transparent;">
                <thead>
                    <tr class="table-secondary align-middle">
                        <th>City</th>
                        <th>Country</th>
                        <th>Population</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in results %}
                        <tr>
                            <td>{{ row.city }}</td>
                            <td>{{ row.country }}</td>
                            <td>{{ row.population }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

world_queries/app/templates/consulta_2.html
{% extends './decorated_base.html' %} 
    {% block datatext %}
    <div class="container-fluid text-center my-5">
        <div style="text-align: center;">
            <h2 class="color1">Consulta 2</h2>
            <h6 class="color6 fw-light">Gobernante de los países con un lengua hablada por al menos el 50% de la población.</h6>
        </div>
        <div class="container-md table-container shadow rounded-5" style="overflow: auto;">
            <form method="GET" action="/2">
                <div class="row mb-3">
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_by">Sort by:</label>
                            <select class="form-select" name="sort_by" id="sort_by">
                                <option value="HeadOfState" {% if request.args.get('sort_by', 'Percentage') == 'HeadOfState' %}selected{% endif %}>Head Of State</option>
                                <option value="Language" {% if request.args.get('sort_by', 'Percentage') == 'Language' %}selected{% endif %}>Language</option>
                                <option value="Percentage" {% if request.args.get('sort_by', 'Percentage') == 'Percentage' %}selected{% endif %}>Percentage</option>
                            </select>
                    </div>
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_order">Order:</label>
                            <select class="form-select" name="sort_order" id="sort_order">
                                <option value="asc" {% if request.args.get('sort_order','desc') == 'asc' %}selected{% endif %}>Ascending</option>
                                <option value="desc" {% if request.args.get('sort_order','desc') == 'desc' %}selected{% endif %}>Descending</option>
                            </select>
                    </div>
                    <div class="col-sm-2 ver-align">
                        <button class="btn btn-secondary" type="submit">Sort</button>
                    </div>
                </div>
            </form>

            <table class="table table-striped table-hover table-borderless " style="background-color: transparent;">
                <thead>
                    <tr class="table-secondary align-middle">
                        <th>Head Of State</th>
                        <th>Language</th>
                        <th>Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in results %}
                        <tr>
                            <td>{{ row.HeadOfState}}</td>
                            <td>{{ row.Language }}</td>
                            <td>{{ row.Percentage }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

world_queries/app/templates/consulta_3.html
{% extends './decorated_base.html' %} 
    {% block datatext %}
    <div class="container-fluid text-center my-5">
        <div style="text-align: center;">
            <h2 class="color1">Consulta 3</h2>
            <h6 class="color6 fw-light">La capital del país con densidad poblacional mas baja que el promedio (de densidad poblacional) de los paises que tienen GNP mayór al promedio mundial.</h6>
        </div>
        <div class="container-md table-container shadow rounded-5" style="overflow: auto;">
            <form method="GET" action="/3">
                <div class="row mb-3">
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_by">Sort by:</label>
                            <select class="form-select"  name="sort_by" id="sort_by">
                                <option value="city" {% if request.args.get('sort_by', 'pdensity') == 'city' %}selected{% endif %}>City</option>
                                <option value="country" {% if request.args.get('sort_by', 'pdensity') == 'country' %}selected{% endif %}>Country</option>
                                <option value="pdensity" {% if request.args.get('sort_by', 'pdensity') == 'pdensity' %}selected{% endif %}>Population Density</option>
                            </select>
                        </div>
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_order">Order:</label>
                            <select class="form-select" name="sort_order" id="sort_order">
                                <option value="asc" {% if request.args.get('sort_order','desc') == 'asc' %}selected{% endif %}>Ascending</option>
                                <option value="desc" {% if request.args.get('sort_order','desc') == 'desc' %}selected{% endif %}>Descending</option>
                            </select>
                    </div>
                    <div class="col-sm-2 ver-align">
                        <button class="btn btn-secondary" type="submit">Sort</button>
                    </div>
                </div>
            </form>

            <table class="table table-striped table-hover table-borderless " style="background-color: transparent;">
                <thead>
                    <tr class="table-secondary align-middle">
                        <th>City</th>
                        <th>Country</th>
                        <th>Population Density (P/km²)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in results %}
                        <tr>
                            <td>{{ row.city }}</td>
                            <td>{{ row.country }}</td>
                            <td>{{ row.pdensity or 'N/A'}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

world_queries/app/templates/consulta_4.html
{% extends './decorated_base.html' %} 
    {% block datatext %}
    <div class="container-fluid text-center my-5">
        <div style="text-align: center;">
            <h2 class="color1">Consulta 4</h2>
            <h6 class="color6 fw-light">El idioma menos hablado de los países que tienen las ciudades menos pobladas.</h6>
        </div>
        <div class="container-md table-container shadow rounded-5" style="overflow: auto;">
            <form method="GET" action="/4">
                <div class="row mb-3">
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_by">Sort by:</label>
                            <select class="form-select" name="sort_by" id="sort_by">
                                <option value="languagepercentage" {% if request.args.get('sort_by', 'population') == 'LanguagePercentage' %}selected{% endif %}>LanguagePercentage</option>
                                <option value="countrylanguage" {% if request.args.get('sort_by', 'population') == 'CountryLanguage' %}selected{% endif %}>CountryLanguage</option>
                                <option value="city" {% if request.args.get('sort_by', 'population') == 'City' %}selected{% endif %}>City</option>
                                <option value="country" {% if request.args.get('sort_by', 'population') == 'Country' %}selected{% endif %}>Country</option>
                                <option value="population" {% if request.args.get('sort_by', 'population') == 'Population' %}selected{% endif %}>Population</option>
                            </select>
                    </div>
                    <div class="col-sm-5">
                        <label class="form-label" for="sort_order">Order:</label>
                            <select class="form-select" name="sort_order" id="sort_order">
                                <option value="asc" {% if request.args.get('sort_order','asc') == 'asc' %}selected{% endif %}>Ascending</option>
                                <option value="desc" {% if request.args.get('sort_order','asc') == 'desc' %}selected{% endif %}>Descending</option>
                            </select>
                    </div>
                    <div class="col-sm-2 ver-align">
                            <button class="btn btn-secondary" type="submit">Sort</button>
                    </div>
                </div>
            </form>

            <table  class="table table-striped table-hover table-borderless " style="background-color: transparent;">
                <thead>
                    <tr class="table-secondary align-middle">
                        <th>Language Percentage</th>
                        <th>Country Language</th>
                        <th>City</th>
                        <th>Country</th>
                        <th>Population</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in results %}
                        <tr>
                            <td>{{ row.languagepercentage }}</td>
                            <td>{{ row.countrylanguage }}</td>
                            <td>{{ row.city }}</td>
                            <td>{{ row.country }}</td>
                            <td>{{ row.population }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

world_queries/app/templates/consulta_5.html
{% extends './decorated_base.html' %} 
{% block datatext %}
<div class="container-fluid text-center my-5">
    <div style="text-align: center;">
        <h2 class="color1">Consulta 5</h2>
        <h6 class="color6 fw-light">Tipo de gobierno de países Africanos con gnp mayor al promedio del continente.</h6>
    </div>
    <div class="table-container">
        <form method="GET" action="/5">
            <div class="row mb-3">
                <div class="col-sm-5">
                    <label class="form-label" for="sort_by">Sort by:</label>
                        <select class="form-select" name="sort_by" id="sort_by">
                            <option value="governmentform" {% if request.args.get('sort_by', 'gnp') == 'GovernmentForm' %}selected{% endif %}>GovernmentForm</option>
                            <option value="name" {% if request.args.get('sort_by', 'gnp') == 'Name' %}selected{% endif %}>Name</option>
                            <option value="gnp" {% if request.args.get('sort_by', 'gnp') == 'GNP' %}selected{% endif %}>GNP</option>
                        </select>
                </div>
                <div class="col-sm-5">
                    <label class="form-label" for="sort_order">Order:</label>
                        <select class="form-select" name="sort_order" id="sort_order">
                            <option value="asc" {% if request.args.get('sort_order','desc') == 'asc' %}selected{% endif %}>Ascending</option>
                            <option value="desc" {% if request.args.get('sort_order','desc') == 'desc' %}selected{% endif %}>Descending</option>
                        </select>
                </div>
                <div class="col-sm-2 ver-align">
                    <button class="btn btn-secondary" type="submit">Sort</button>
                </div>
            </div>
        </form>

        <table class="table table-striped table-hover table-borderless " style="background-color: transparent;">
            <thead>
                <tr class="table-secondary align-middle">
                    <th>Government Form</th>
                    <th>Name</th>
                    <th>GNP</th>
                </tr>
            </thead>
            <tbody>
                {% for row in results %}
                    <tr>
                        <td>{{ row.governmentform }}</td>
                        <td>{{ row.name }}</td>
                        <td>{{ row.gnp }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

world_queries/app/templates/decorated_base.html
{% extends './base.html' %} 
    {% block title %} WORLD QUERIES {% endblock %} 
    {% block content %}
    <div class="container-fluid title my-4 shadow">
        <div class="title-img">
            <img src="{{ url_for('static', filename='images/earth.jpeg') }}" alt="">
        </div>
        <h1 class="text-overlay color4 fw-light">
            W<i class="bi bi-globe-americas color4"></i>RLD QUERIES 
        </h1>
    </div>
        {% block datatext %}
        
        {% endblock %}
    {% endblock %}